// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "d679d285-5828-4039-b520-e5bf5e5db390");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1540534977);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1540535097);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1540592854);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1540584759);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1540584639);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1540062069);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1540535217);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1538711069);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 68);
user_pref("browser.newtabpage.activity-stream.impressionId", "{cc04abde-484b-447c-8e5a-125f83061c67}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1538697600);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1540591176757");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1540594776757");
user_pref("browser.search.countryCode", "IT");
user_pref("browser.search.region", "IT");
user_pref("browser.shell.checkDefaultBrowser", true);
user_pref("browser.shell.mostRecentDateSetAsDefault", "1538711073");
user_pref("browser.slowStartup.averageTime", 3006);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20180712122436");
user_pref("browser.startup.homepage_override.mstone", "61.0.1");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"bestproxyswitcher_bestproxyswitcher_com-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"]},\"seen\":[\"developer-button\",\"bestproxyswitcher_bestproxyswitcher_com-browser-action\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1538711075672");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.iniFile.exists.appversion", "61.0.1");
user_pref("distribution.iniFile.exists.value", false);
user_pref("extensions.blocklist.lastModified", "Mon, 08 Oct 2018 10:58:55 GMT");
user_pref("extensions.blocklist.pingCountTotal", 15);
user_pref("extensions.blocklist.pingCountVersion", 15);
user_pref("extensions.databaseSchema", 26);
user_pref("extensions.getAddons.cache.lastUpdate", 1540534978);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "61.0.1");
user_pref("extensions.lastPlatformVersion", "61.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webextensions.uuids", "{\"webcompat@mozilla.org\":\"76ba9d91-8d64-4922-94ef-7b8a09aa883d\",\"screenshots@mozilla.org\":\"319fd373-90d7-46d0-a2b4-07d14fa45c8e\",\"bestproxyswitcher@bestproxyswitcher.com\":\"9ff2d5d8-3018-4b6e-ab03-282ac658f5e2\"}");
user_pref("idle.lastDailyNotification", 1540442212);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1538711118);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20180712122436");
user_pref("media.gmp-manager.lastCheck", 1538711116);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.database.lastMaintenance", 1540442212);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "938265f1-10f1-4f8a-8d67-99c8631ec905");
user_pref("services.blocklist.addons.checked", 1540535029);
user_pref("services.blocklist.gfx.checked", 1540535029);
user_pref("services.blocklist.onecrl.checked", 1540535029);
user_pref("services.blocklist.pinning.checked", 1540535029);
user_pref("services.blocklist.plugins.checked", 1540535029);
user_pref("services.settings.clock_skew_seconds", 68);
user_pref("services.settings.last_etag", "\"1540500294078\"");
user_pref("services.settings.last_update_seconds", 1540535029);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1538711429);
user_pref("toolkit.startup.last_success", 1538711067);
user_pref("toolkit.telemetry.cachedClientID", "08f2acea-da1e-415b-9ab5-5777b63e92b3");
user_pref("toolkit.telemetry.previousBuildID", "20180712122436");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
